[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "demangler"
version = "1.0.0"
description = "demangler"

[tools.setuptools.packages.find]
where = ["src"]